import{o as a,c as n,k as s,q as c,s as r,A as l,e,a6 as t}from"../modules/vue-BIeBYBLx.js";import{I as u}from"./default-D2C4euab.js";import{aT as o}from"../index-CMbpHyp1.js";import{p,u as i,f as d}from"./context-Cc2GRSkm.js";import"../modules/shiki-0tBZ1x7C.js";const m=e("h1",null,"Une levée d’Exception implique",-1),h=e("ul",null,[e("li",null,[e("p",null,"Recherche dans la méthode courante un bloc catch acceptant cette exception.")]),e("li",null,[e("p",null,[t("Si aucun bloc catch n’est trouvé et que l’exception est une sous-classe de "),e("em",null,"java.lang.Exception"),t(", alors la méthode doit déclarer l’exception dans sa clause "),e("em",null,"throws"),t(", et l’exception est propagée à l’appelant.")])]),e("li",null,[e("p",null,"L’appel à une méthode pouvant lever une exception doit :"),e("ul",null,[e("li",null,[t("soit être contenu dans un bloc "),e("em",null,"try/catch")]),e("li",null,[t("soit être situé dans une méthode propageant ("),e("em",null,"throws"),t(") cette classe d’exception")])])])],-1),w={__name:"37",setup(x){return p(o),i(),(_,f)=>(a(),n(u,c(r(l(d)(l(o),36))),{default:s(()=>[m,h]),_:1},16))}};export{w as default};
